set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TARGET_TRIPLE aarch64-apple-darwin)
set(TOOLCHAIN_PREFIX ${TARGET_TRIPLE})

include(${CMAKE_CURRENT_LIST_DIR}/resolve_macos_sdk.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/detect_compiler.cmake)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)