set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TARGET_TRIPLE x86_64-unknown-linux-gnu)
set(TOOLCHAIN_PREFIX x86_64-linux-gnu)

if(NOT DEFINED CMAKE_SYSROOT)
    if(DEFINED ENV{LINUX_SYSROOT})
        set(CMAKE_SYSROOT $ENV{LINUX_SYSROOT})
    endif()
endif()

if(NOT CMAKE_SYSROOT)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/detect_compiler.cmake)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)